### ISSUE TITLE
Quest: Pass TodoMVC spec

### ISSUE THREAD

**Issue by mmun** [glimmerjs/todomvc-demo#3]
Please help getting this glimmer app up to spec!

[TodoMVC Spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md#application-specification)

We can skip over the sections pertaining to getting the app included into the todomvc repo itself.

If you want to tackle an item, please leave a comment saying so and we'll 🔒 it down for you.

## [Dependency Management](https://github.com/tastejs/todomvc/blob/master/app-spec.md#dependency-management)

- [x] Import `todomvc-app-css` from NPM. (:lock: @michalsnik #5)
- [x] Import `todomvc-common` from NPM
  - [x] Styles (:lock: @michalsnik #5)
  - [x] JavaScript: (🔒 @michalsnik #11)
## [Functionality](https://github.com/tastejs/todomvc/blob/master/app-spec.md#functionality)

- [x] [No todos](https://github.com/tastejs/todomvc/blob/master/app-spec.md#no-todos)
- [x] [New todo](https://github.com/tastejs/todomvc/blob/master/app-spec.md#new-todo)
- [x] [Mark all as complete](https://github.com/tastejs/todomvc/blob/master/app-spec.md#mark-all-as-complete) (:lock: @GavinJoyce #2)
- [x] [Item](https://github.com/tastejs/todomvc/blob/master/app-spec.md#item)
- [x] [Editing](https://github.com/tastejs/todomvc/blob/master/app-spec.md#editing) (:lock: @michalsnik #5)
- [x] [Counter](https://github.com/tastejs/todomvc/blob/master/app-spec.md#counter)
- [x] [Clear completed button](https://github.com/tastejs/todomvc/blob/master/app-spec.md#clear-completed-button)
- [x] [Persistence](https://github.com/tastejs/todomvc/blob/master/app-spec.md#persistence) (:lock: @Martodox #10)
- [x] [Routing](https://github.com/tastejs/todomvc/blob/master/app-spec.md#routing) (:lock: @michalsnik #7)

## Tests

- [ ] [No todos](https://github.com/tastejs/todomvc/blob/master/app-spec.md#no-todos)
- [ ] [New todo](https://github.com/tastejs/todomvc/blob/master/app-spec.md#new-todo)
- [ ] [Mark all as complete](https://github.com/tastejs/todomvc/blob/master/app-spec.md#mark-all-as-complete)
- [ ] [Item](https://github.com/tastejs/todomvc/blob/master/app-spec.md#item)
- [ ] [Editing](https://github.com/tastejs/todomvc/blob/master/app-spec.md#editing)
- [ ] [Counter](https://github.com/tastejs/todomvc/blob/master/app-spec.md#counter)
- [ ] [Clear completed button](https://github.com/tastejs/todomvc/blob/master/app-spec.md#clear-completed-button)
- [ ] [Persistence](https://github.com/tastejs/todomvc/blob/master/app-spec.md#persistence)
- [ ] [Routing](https://github.com/tastejs/todomvc/blob/master/app-spec.md#routing)

Unfortunately, the glimmer app build pipeline doesn't support tests yet. We can try to build a test harness manually for now or just wait for the pipeline to be updated.

**Comment by michalsnik** [comment]
Actually importing styles from NPM is possible, but using Broccoli's `Funnel` and `MergeTrees`. If I remember correctly, like so:
```js
const Funnel = require('broccoli-funnel');
const MergeTrees = require('broccoli-merge-trees');

// ...

const todoMVCStyles = new Funnel('node_modules', {
  files: ['todomvc-app-css/index.css', 'todomvc-common/base.css'],
});

return  new MergeTrees([app.toTree(), todoMVCStyles]);
```

**Comment by Martodox** [comment]
Hi there,
getting exited for the glimmer with TS. I can tackle the Persistence requirement.

Have you guys have slack or anything to keep in touch?

**Comment by GavinJoyce** [comment]
> Have you guys have slack or anything to keep in touch?

@Martodox there is `-glimmer` and `dev-glimmer` on the [Ember Community Slack](https://embercommunity.slack.com/). You can [join here](https://ember-community-slackin.herokuapp.com/).

**Comment by mmun** [comment]
Thanks @michalsnik! That slipped my mind.

**Comment by michalsnik** [comment]
Do we actually wan't do tackle routing in this app too? I think that current solution is sufficient at the moment and demonstrates glimmer capabilities quite accurate.

**Comment by michalsnik** [comment]
Ah nvm, I see now in official TodoMVC specification that it's required.

**Comment by mmun** [comment]
@michalsnik To be honest, I'm not sure how closely we want to align with the specification. In order to get it merged into the repo you need to follow their code style and stuff like that which doesn't align well with the strong conventions that Glimmer and Ember have.

**Comment by michalsnik** [comment]
On the other hand it might be a good example of how to implement simple routing in glimmer app. I'll try to prepare a PR.
